apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-next
  namespace: demo
spec:
  ingressClassName: haproxy
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-next
                port:
                  number: 80